<?php
/**
 * Created by PhpStorm.
 * User: rxw
 * Date: 2017/9/2
 * Time: 12:11
 */
namespace framework\web;

abstract class Api extends \framework\base\Controller
{
    public function afterAction($data = array())
    {
        return $data;
    }

    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $urlComponent = $this->getComponent('response');
        $urlComponent->noCache();
        $urlComponent->contentType('json');
        unset($urlComponent);
    }

    protected function getCache()
    {
        return $this->getComponent('cache');
    }

    protected function sendFile($path, $type = 'jpg')
    {
        $urlComponent = $this->getComponent('response');
        $urlComponent->contentType($type);
        $urlComponent->sendFile($path);
        return $path;
    }

    protected function addTask($className, $funcName, $params, $taskId = -1, $isAsync = false)
    {
        if (!$isAsync)
        {
            $this->getComponent('taskManager')->addTask($className, $funcName, $params, $taskId);
        }
        else
        {
            $this->getComponent('taskManager')->addAsyncTask($className, $funcName, $params, $taskId);
        }
    }

    public function addTimer($timeStep, callable $callable, $params= array())
    {
        return $this->getComponent('server')->getServer()->addTimer($timeStep, $callable, $params);
    }

    public function addTimerAfter($timeStep, callable $callable, $params= array())
    {
        return $this->getComponent('server')->getServer()->addTimerAfter($timeStep, $callable, $params);
    }
}