<?php
/**
 * Created by PhpStorm.
 * User: rxw
 * Date: 2017/9/2
 * Time: 12:11
 */
namespace framework\web;

abstract class Api extends \framework\base\Controller
{
    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $urlComponent = $this->getComponent('response');
        $urlComponent->noCache();
        $urlComponent->contentType('json');
        unset($urlComponent);
    }

    protected function getCache()
    {
        return $this->getComponent('cache');
    }

    protected function sendFile($path, $type = 'jpg')
    {
        $urlComponent = $this->getComponent('response');
        $urlComponent->contentType($type);
        $urlComponent->sendFile($path);
        return $path;
    }
}