<?php
/**
 * Created by PhpStorm.
 * User: rxw
 * Date: 2017/9/2
 * Time: 12:11
 */
namespace framework\web;

abstract class WebSocket extends Controller
{
    protected $_responseData = [];


    protected function afterInit()
    {
        
    }

    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->afterInit();
    }

    protected function send($fd, $data, $now = false)
    {
      $this->server->getServer()->push($fd, $data, $now);
    }

    protected function fd()
    {
      return $this->server->getServer()->fd();
    }

    protected function assign($key, $value = null)
    {
        $this->_responseData[$key] = $value;
    }

    protected function display($path = '')
    {
        return $this->_responseData;
    }
}