<?php
/**
 * Created by PhpStorm.
 * User: rxw
 * Date: 18-4-9
 * Time: 下午9:32
 */
namespace framework\components\log;


class Seaslog extends Log
{
    public function save($data)
    {
        parent::save($data); // TODO: Change the autogenerated stub
    }

    public function write($data, $path)
    {
        return parent::write($data, $path); // TODO: Change the autogenerated stub
    }
}