<?php
/**
 * Created by PhpStorm.
 * User: rxw
 * Date: 17-9-16
 * Time: 下午8:48
 */
namespace framework\server;

use framework\base\Container;

class HttpServer extends BaseServer
{
    protected function init()
    {
        $hasOnRequest = false;
        if (!$this->_server) {
            $hasOnRequest = true;
            $this->_server = new \swoole_http_server($this->_conf['ip'], $this->_conf['port']);
        }

        parent::init(); // TODO: Change the autogenerated stub

        if ($hasOnRequest) {
            $this->onRequest();
        }

    }

    protected function execApp(&$response)
    {
        // TODO: Implement execApp() method.
        $response->hasEnd = false;
        $container = Container::getInstance();
        $urlInfo = $container->getComponent(SYSTEM_APP_NAME, 'url')->run();
        $response->system = $urlInfo['system'];



        if ($urlInfo !== false) {
            $container->getComponent(SYSTEM_APP_NAME, 'dispatcher')->setSystem($urlInfo['system']);
            // 初始化配置项
            if (!$container->appHasComponents($urlInfo['system'])) {
                $appConf = require_once APP_ROOT. '/' .$urlInfo['system'] . '/conf/conf.php';
                $appConf['addComponentsMap'] = $appConf['addComponentsMap'] ?? [];
                $container->addComponents($urlInfo['system'], $appConf['addComponentsMap']);
                $container->setAppComponents($urlInfo['system'] ,array(
                    'components' => $appConf['components'],
                    'composer' => $appConf['composer']
                ));
            }


            $result = $container->getComponent(SYSTEM_APP_NAME, 'dispatcher')->run($urlInfo);
            $container->getComponent(SYSTEM_APP_NAME, 'cookie')->send($response);
            $response->hasEnd = $container->getComponent(SYSTEM_APP_NAME, 'response')->send($response, $result);
            $container->getComponent(SYSTEM_APP_NAME, 'dispatcher')->setSystem('');
            unset($result);
        }

        unset($container);
    }

    protected function onRequest()
    {
        $this->_server->on("request", function (\swoole_http_request $request,\swoole_http_response $response)
        {
            if (DEBUG)
            {
                ob_start();
            }
            if ($this->_event)
            {
                $this->_event->onRequest($request,$response);
            }
            $container = Container::getInstance();
            if (!empty($request->get)) {
                $_GET = $request->get;
            }
            if (!empty($request->post)) {
                $_POST = $request->post;
            }
            if (!empty($request->files)) {
                $_FILES = $request->files;
//                $container->getComponent('upload')->save('file'); 上传文件测试
            }
            if (!empty($request->cookie)) {
                $_COOKIE = $request->cookie;
            }


            try
            {
                if ($this->_event)
                {
                    $this->_event->onResponse($request,$response);
                }
                $request->server['HTTP_HOST'] = $request->header['host'];
                foreach ($request->server as $key => $item)
                {
                    $request->server[strtoupper($key)] = $item;
                    unset($request->server[$key]);
                }
                $_SERVER = $request->server;



                $this->execApp($response);
            }
            catch (\Throwable $exception)
            {
                $code = $exception->getCode() > 0 ? $exception->getCode() : 404;
                $response->status($code);
                if (DEBUG) {
                    $result = ob_get_clean();
                    $response->write($result . $exception->getMessage().$exception->getTraceAsString());
                }
                $this->handleException($exception);
            }



            if (!$response->hasEnd) {
                $response->end();
            }
            $_GET = [];
            $_POST = [];
            $_FILES = null;
            $_COOKIE = [];
            $_SERVER = [];
            if (!empty($response->system)) {
                $container->finish($response->system);
            }
            $container->finish(SYSTEM_APP_NAME);
            unset($container,$request,$response, $urlInfo);
        });
    }
}