<?php
namespace framework\server;

class RpcServer extends BaseServer
{
    protected function init()
    {
        $this->_server = new \swoole_http_server($this->_conf['ip'], $this->_conf['port']);
        return parent::init(); // TODO: Change the autogenerated stub
    }
}