<?php
/**
 * Created by PhpStorm.
 * User: rxw
 * Date: 17-9-16
 * Time: 下午8:48
 */
namespace framework\server;

class TcpServer extends BaseServer
{
    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function send($fd, $data, $eof = '')
    {
      $this->_server->send($fd, $data . $eof);
    }
}