<?php
/**
 * Created by PhpStorm.
 * User: rxw
 * Date: 17-9-16
 * Time: 下午8:48
 */
namespace framework\server;

use framework\base\Container;

class TcpServer extends BaseServer
{
    protected function init()
    {
        if (!$this->_server) {
          $this->_server = new \swoole_server($this->_conf['ip'], $this->_conf['port']);
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function send($fd, $data, $eof = '')
    {
      $this->_server->send($fd, $data . $eof);
    }
}