<?php
/**
 * Created by PhpStorm.
 * User: rxw
 * Date: 17-9-16
 * Time: 下午8:54
 */
namespace framework\server;

class WebSocketServer extends BaseServer
{
    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->onRequest();
        $this->_server = new  \swoole_websocket_server($this->_appConf['ip'], $this->_appConf['port']);
    }

    public function onRequest()
    {
        $this->_server->on("request", function (\swoole_http_request $request,\swoole_http_response $response)
        {
            if (!empty($this->_event))
            {
                $this->_event->onRequest($request,$response);
            }

            try
            {
                var_dump($request);
            }
            catch (\Exception $exception)
            {
                throw $exception;
            }

            if (!empty($this->_event))
            {
                $this->_event->onResponse($request,$response);
            }


            if(!empty($write)){
                $response->write($write);
            }
            $response->end();
        });
    }
}