<?php
/**
 * Created by PhpStorm.
 * User: rxw
 * Date: 18-4-22
 * Time: 下午7:36
 */

namespace framework\conformancehash;
class ConformanceHash extends DoubleList
{
    public function addNode(Node &$node)
    {
        if(!parent::addNode($node)){
            return false;
        } // TODO: Change the autogenerated stub

        $this->resetVirtualNode();
    }

    public function removeNode(Node &$node)
    {
        if (!parent::removeNode($node)) {
            return false;
        } // TODO: Change the autogenerated stub

        $this->resetVirtualNode();
    }

    protected function resetVirtualNode()
    {
//        $node = $this->_node;
//        $stepL = (2 << 32) / $this->_length;
//        while ($node->_next) {
//            if (($node->_next->_value - $node->_value) >= $stepL) {
//
//            }
//        }
    }

    public function findNodeByValue($value)
    {
        if ($this->_length == 1) {
            return $this->_node;
        }
        $value = crc32($value) % (2 << 8);
        $node = $this->_node;
        while ($node->_next) {
            if (($value >= $node->_value && $value < $node->_next->_value) ||
                $value >= $node->_value && $node->_next->_isFirst) {
                if ($value == $node->_value) {
                    return $node;
                } else {
                    return $node->_next;
                }
            } else {
                $node = $node->_next;
            }
        }

        return $node;
    }
}